# Generated by Django 5.1.7 on 2025-04-18 07:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=100)),
                ('building_created_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('sensor_last_modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reading', models.FloatField()),
                ('sensor_reading_last_modified_date', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('tank_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacity', models.FloatField()),
                ('tank_created_date', models.DateTimeField()),
                ('tank_last_modified_date', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.tank'),
        ),
    ]
